baseURL = "https://ethaan.github.io/webpage/"
languageCode = "en-us"
title = "Ethan Escareño Rosano"
theme = "tailwindcss"
publishDir = "docs"

[taxonomies]
    tag = "software"

[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
    author = "Ethan Escareño"
    avatar = "ethan.jpeg"
    description = "Ethan Escareño Rosano, Software Engineer"
    tagline = "Software Engineer interested on Python, Javascript and Swift"
